### ISSUE TITLE
WOA2005 dataset generates error in esmlab

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/marbl-diags#10]
When running

```
$ ./driver.py -i sample_input_files/woa2005.yml
```

I get the following error

```
INFO (_plot_climo): generating plot: state-map-woa2005-comp_nitrate_0m_ANN
/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/xarray/core/nanops.py:161: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)
INFO (_plot_climo): Plotting NO3 from WOA2005
Traceback (most recent call last):
  File "./driver.py", line 45, in <module>
    AnalysisElement.do_analysis()
  File "/gpfs/fs1/work/mlevy/codes/marbl-diags/marbl_diags/analysis_elements_class.py", line 122, in do_analysis
    func(self, self._config_dict)
  File "/gpfs/fs1/work/mlevy/codes/marbl-diags/marbl_diags/analysis_ops.py", line 26, in plot_ann_climo
    _plot_climo(AnalysisElement, config_dict, valid_time_dims)
  File "/gpfs/fs1/work/mlevy/codes/marbl-diags/marbl_diags/analysis_ops.py", line 137, in _plot_climo
    fmean = esmlab.statistics.weighted_mean(field, TAREA).load().values
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/esmlab/statistics.py", line 107, in weighted_mean
    weights = _apply_nan_mask(x, weights, avg_over_dims_v)
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/esmlab/statistics.py", line 21, in _apply_nan_mask
    (weights / weights.sum(avg_over_dims_v)).sum(avg_over_dims_v), 1.0
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/glade/work/mlevy/miniconda3/envs/NPL-conda/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(1., dtype=float32)
 y: array(1.)
```

At first glance it looks like maybe a single-precision vs double-precision issue, and I'll open an issue in esmlab as well because I think I can point @andersy005 in the right direction. In the mean time, commenting out `stats_in_title: True` in the YAML file allows plots to be generated (without adding min, max, etc to the title)

**Comment by andersy005** [comment]
@mnlevy1981, I will look into it once I have some free cycles

**Comment by mnlevy1981** [comment]
@andersy005 Thanks! As promised, I set up an issue in esmlab as well.

**Comment by mnlevy1981** [comment]
Fixed in esmlab
